# Generated by Django 5.2.7 on 2025-10-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_embarque', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mejillón', max_length=100)),
                ('tipo', models.CharField(choices=[('fresco', 'Fresco'), ('congelado', 'Congelado'), ('conserva', 'En conserva')], max_length=20)),
                ('presentacion', models.CharField(max_length=100)),
                ('precio_kg_usd', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('naviera', 'Naviera'), ('forwarder', 'Forwarder'), ('aduana', 'Agente de aduana'), ('flete', 'Flete terrestre'), ('broker', 'Broker'), ('otro', 'Otro')], max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dus', models.BooleanField(default=False)),
                ('guia_despacho', models.BooleanField(default=False)),
                ('packing_list', models.BooleanField(default=False)),
                ('certificado_origen', models.BooleanField(default=False)),
                ('otros_certificados', models.TextField(blank=True)),
                ('fecha_arribo_estimada', models.DateField()),
                ('plazo_envio_courier', models.DateField()),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada')], default='pendiente', max_length=20)),
                ('embarque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp_app.embarque')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('materia_prima', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp_app.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_entrada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rendimiento_esperado_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kg_salida_real', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('abastecido_a_inventario', models.BooleanField(default=False)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_app.materiaprima')),
                ('producto_terminado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_app.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='CostoMaquila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('CLP', 'CLP')], default='USD', max_length=3)),
                ('fecha', models.DateField()),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='erp_app.operacionprocesamiento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada')], default='pendiente', max_length=20)),
                ('porcentaje_adelanto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condicion_saldo', models.CharField(choices=[('contra_copia', 'Contra copia de documentos'), ('contra_originales', 'Contra recepción de documentos originales')], max_length=50)),
                ('fecha_estimada_pago_saldo', models.DateField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_app.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='embarque',
            name='orden_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.ordenventa'),
        ),
        migrations.CreateModel(
            name='ItemOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp_app.ordenventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_app.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioProductoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_kg', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp_app.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_estimado_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margen_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_sugerido_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('convertida_a_orden', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_app.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_app.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='CompraMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('CLP', 'CLP')], default='USD', max_length=3)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('abastecida', models.BooleanField(default=False)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.materiaprima')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_referencia', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('CLP', 'CLP')], default='USD', max_length=3)),
                ('fecha_vencimiento', models.DateField()),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=20)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='erp_app.embarque')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_app.proveedorservicio')),
            ],
        ),
    ]
