# Generated by Django 5.2.7 on 2025-10-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_ordenventa_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenventa',
            name='operacion',
        ),
    ]
